//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VR_DemCreator.rc
//
#define IDOK2                           2
#define ID_CCUCLATE                     2
#define IDSEARCH                        2
#define IDD_SET_STAT_DLG                7000
#define IDC_LIST_CTRL                   7000
#define IDC_STATIC_PIC                  7001
#define IDB_BACKGROUND                  7002
#define IDC_MAX_SLOPE                   7002
#define IDD_SET_SEMIVARIOGRAM_DLG       7003
#define IDC_MIN_SLOPE                   7003
#define IDD_SET_SLOPE_DLG               7004
#define IDC_AVERAGE_SLOPE               7004
#define IDC_STATIC_HIST                 7005
#define IDD_SETREMAINSERROR_DLG         7005
#define IDD_SET_REMAINSERROR_DLG        7005
#define IDD_SET_LIMIT_DLG               7006
#define IDC_LIST_STATS                  7007
#define IDD_SET_GRIDCREATOR_IDW_DLG     7007
#define IDD_SET_GRIDCREATOR_RBF_DLG     7008
#define IDC_EDIT_LIMIT                  7009
#define IDD_SET_GRIDCREATOR_KRG_DLG     7009
#define IDC_RADIO_GLOBAL                7010
#define IDC_RADIO_FOURDIRECTION         7011
#define IDD_SET_GRIDCREATOR_PLY_DLG     7011
#define IDC_RADIO_EIGHTDIRECTION        7012
#define IDC_POINTCOUNT_PREDIRECTION     7013
#define IDD_SET_GRIDCREATOR_SPD_DLG     7013
#define IDC_POINTCOUNT_TOTAL            7014
#define IDD_SET_CURVATURE_DLG           7014
#define IDC_EDIT_SEARCHRADIUS           7015
#define IDD_SET_CALCHEIGHT_DLG          7015
#define IDC_EDIT_NUMX                   7016
#define IDD_SET_TERRAINFACTOR_DLG       7016
#define IDC_EDIT_NUMY                   7017
#define IDD_SET_FRACTAL_DLG             7017
#define IDC_EDIT_SIZEX                  7018
#define IDD_SET_FRACTALRESULT_DLG       7018
#define IDC_EDIT_SIZEY                  7019
#define IDD_SET_TERRAINRELIF_DLG        7019
#define IDC_EDIT_PATHANME               7020
#define IDD_SET_TERRAINRELIFRESULT_DLG  7020
#define IDC_BUTTON_PATH                 7021
#define IDD_SET_TERRAINCV_DLG           7021
#define IDC_EDIT_U                      7022
#define IDD_SET_TERRAINCVRESULT_DLG     7022
#define IDC_EDIT_T                      7023
#define IDD_SET_CELLCOUNT_DLG           7023
#define IDC_COMBO_METHOD                7024
#define IDD_SET_MATINFO_DLG             7024
#define IDC_EDIT_C0                     7025
#define IDD_SET_LOCALTC_DLG             7025
#define IDC_EDIT_C                      7026
#define IDD_SET_IDWPARAM_DLG            7026
#define IDC_EDIT_ALFA                   7027
#define IDD_SET_SPDPARAM_DLG            7027
#define IDC_EDIT_A                      7027
#define IDC_BUTTON_VARIO                7028
#define IDD_SET_RBFPARAM_DLG            7028
#define IDC_RADIO_INTERPOLATION_NH      7029
#define IDD_SET_KRGPARAM_DLG            7029
#define IDC_RADIO_INTERPOLATION_CZ      7030
#define IDD_SET_CACLLSD_DLG             7030
#define IDC_COMBO_INTERPOLATION         7031
#define IDC_RADIO_SAMPLEDISTANCE        7032
#define IDC_RADIO_CUSTOMDISTANCE        7033
#define IDB_LISHUDU                     7033
#define IDC_EDIT_MAXDISTANCE            7034
#define IDD_SET_RECOMBINETE_DLG         7034
#define IDD_SET_IMPORTTXT_DLG           7035
#define IDC_EDIT_MINDISTANCE            7035
#define IDC_CHECK_RE                    7036
#define IDD_SET_DIMENSIONANALYSE_DLG    7036
#define IDC_ONLY                        7037
#define IDD_SET_SEARCHPOINT_DLG         7037
#define IDC_BTN_PATH                    7038
#define IDD_SET_SEARCHPOINTEX_DLG       7038
#define IDD_SET_WINDOWNSIZE             7039
#define IDD_SET_DELTAHPER_DLG           7040
#define IDC_EDIT_PATHNAME               7041
#define IDC_BROWN                       7042
#define IDD_SET_CHECKPOINT_DLG          7042
#define IDC_PATHNAME                    7043
#define IDC_EDIT_SIZE_X                 7044
#define IDC_EDIT_SIZE_Y                 7045
#define IDC_EDIT_NUM_X                  7046
#define IDC_EDIT_NUM_Y                  7047
#define IDC_EDIT_ZSCALE                 7048
#define IDC_EDIT_SCALE                  7049
#define IDC_LIST_SCALE                  7050
#define IDC_BUTTON_ADD                  7051
#define IDC_BUTTON_DEL                  7052
#define IDC_EDIT_RESULT_1               7054
#define IDC_EDIT_RESULT_2               7055
#define IDC_EDIT_DEMNAME                7056
#define IDC_EDIT_WINDOWSIZE             7057
#define IDC_EDIT_WINDOWRANGE            7058
#define IDC_EDIT_MAX                    7060
#define IDC_EDIT_MIN                    7061
#define IDC_EDIT_X                      7061
#define IDC_EDIT_MEAN                   7062
#define IDC_EDIT_Y                      7062
#define IDC_RADIO_KERNAL                7062
#define IDC_RADIO_KERNAL2               7063
#define IDC_EDIT_LEFT                   7063
#define IDC_EDIT_RIGHT                  7064
#define IDC_STATIC_DRAW                 7064
#define IDC_EDIT_TOP                    7065
#define IDC_EDIT_BOTTOM                 7066
#define IDC_EDIT_PRE_POINTNUM           7066
#define IDC_EDIT_MATHEIGHT              7067
#define IDC_EDIT_TOTAL_POINTNUM         7067
#define IDC_EDIT_MATWIDTH               7068
#define IDC_EDIT_POINTPATTERN           7068
#define IDC_EDIT_HEIGHT                 7069
#define IDC_EDIT_MEANSLOPE              7069
#define IDC_EDIT_WIDTH                  7070
#define IDC_EDIT_MEANROUGHNESS          7070
#define IDC_RADIO_NULLDIRECTION         7071
#define IDC_EDIT_RADIUS                 7072
#define IDC_EDIT_Z                      7073
#define IDC_BUTTON_IDW                  7074
#define IDC_EDIT_NUMATTRIB              7074
#define IDC_BUTTON_SPD                  7075
#define IDC_BUTTON_RBF                  7076
#define IDC_BUTTON_MQF                  7076
#define IDC_BUTTON_KRG                  7077
#define IDC_BUTTON_MLF                  7077
#define IDC_EDIT_IDW_Z                  7078
#define IDC_BUTTON_TPSF                 7078
#define IDC_EDIT_SPD_Z                  7079
#define IDC_BUTTON_NCSF                 7079
#define IDC_EDIT_RBF_Z                  7080
#define IDC_BUTTON_EXP                  7080
#define IDC_EDIT_KRG_Z                  7081
#define IDC_RADIO_MQF                   7081
#define IDC_BUTTON_LINE                 7081
#define IDC_RADIO_IQMF                  7082
#define IDC_EDIT_CENTROD                7082
#define IDC_RADIO_TPSF                  7083
#define IDC_RADIO_MLF                   7084
#define IDC_RADIO_NCSF                  7085
#define IDC_RADIO_QX                    7087
#define IDC_RADIO_ZS                    7088
#define IDC_RADIO_GS                    7089
#define IDC_EDIT_VALUE                  7092
#define ID_CALC                         7093
#define IDC_EDIT_D                      7094
#define IDC_EDIT_VALUE2                 7095
#define IDC_EDIT_REPATHNAME             7095
#define IDC_EDIT_VALUE3                 7096
#define IDC_EDIT_TEPATHNAME             7096
#define IDC_EDIT_VALUE4                 7097
#define IDC_EDIT_COMPATHNAME            7097
#define IDC_EDIT_VALUE5                 7098
#define IDC_BUTTON_RE                   7098
#define IDC_BUTTON_TE                   7099
#define IDC_BUTTON_COM                  7100
#define IDC_BUTTON_RE2                  7101
#define IDC_EDIT_TXT_PATHNAME           7102
#define IDC_BUTTON_RE3                  7102
#define IDC_BUTTON_TXT                  7103
#define IDC_BUTTON_RE4                  7103
#define IDC_BUTTON_RE5                  7104
#define IDC_CHECK_FIRSTLINE             7105
#define IDC_BUTTON_RE6                  7105
#define IDC_EDIT_REPATHNAME2            7106
#define IDC_RADIO_1                     7107
#define IDC_EDIT_REPATHNAME3            7107
#define IDC_RADIO_2                     7108
#define IDC_EDIT_REPATHNAME4            7108
#define IDC_RADIO_3                     7109
#define IDC_BUTTON_PATHNAME             7109
#define IDC_EDIT_REPATHNAME5            7109
#define IDC_EDIT_FIELDNUM               7110
#define IDC_EDIT_REPATHNAME6            7110
#define IDC_RADIO_MODE_1                7111
#define IDC_BUTTON_TE2                  7111
#define IDC_RADIO_MODE_2                7112
#define IDC_EDIT_TEPATHNAME2            7112
#define IDC_RADIO_MODE_3                7113
#define IDC_BUTTON_TE3                  7113
#define IDC_RADIO_MODE_4                7114
#define IDC_EDIT_TEPATHNAME3            7114
#define IDC_RADIO_DELIMS_1              7115
#define IDC_BUTTON_TE4                  7115
#define IDC_RADIO_DELIMS_2              7116
#define IDC_EDIT_TEPATHNAME4            7116
#define IDC_RADIO_DELIMS_3              7117
#define IDC_BUTTON_TE5                  7117
#define IDC_EDIT_TEPATHNAME5            7118
#define IDC_EDIT_SLOPE                  7118
#define IDC_BUTTON_TE6                  7119
#define IDC_EDIT_DH                     7119
#define IDC_EDIT_TEPATHNAME6            7120
#define IDC_EDIT_NUM                    7120
#define IDC_LIST_COORD                  7121
#define IDC_BUTTON_LSD                  7121
#define IDGO                            7122
#define IDC_BUTTON_LSD2                 7122
#define IDC_BUTTON_LSD3                 7123
#define IDC_EDIT_SIZE                   7124
#define IDC_BUTTON_LSD4                 7124
#define IDC_CHECK_SLOPE                 7125
#define IDC_BUTTON_LSD5                 7125
#define IDC_CHECK_PATTERN               7126
#define IDC_BUTTON_LSD6                 7126
#define IDC_CHECK_DISTANCE              7127
#define IDC_CHECK_PINGYUAN              7128
#define IDC_CHECK_QIULING               7129
#define IDC_CHECK_SHANDI                7130
#define IDC_CHECK_DISHAN                7130
#define IDC_EDIT_MIN_SLOPE              7131
#define IDC_CHECK_ZHONGSHAN             7131
#define IDC_EDIT_MAX_SLOPE              7132
#define IDC_CHECK_GAOSHAN               7132
#define IDC_EDIT_MIN_PATTERN            7133
#define IDC_CHECK_HUNHE                 7133
#define IDC_EDIT_MAX_PATTERN            7134
#define IDC_EDIT_MIN_DISTANCE           7135
#define IDC_EDIT_MAX_DISTANCE           7136
#define IDC_EDIT_MIN_PINGYUAN           7137
#define IDC_EDIT_MAX_PINGYUAN           7138
#define IDC_EDIT_MIN_QIULING            7139
#define IDC_EDIT_MAX_QIULING            7140
#define IDC_EDIT_MIN_SHANDI             7141
#define IDC_EDIT_MAX_SHANDI             7142
#define IDC_EDIT_IDW                    7144
#define IDC_EDIT_SPD                    7145
#define IDC_EDIT_MQF                    7146
#define IDC_EDIT_MLF                    7147
#define IDC_EDIT_TPSF                   7148
#define IDC_EDIT_NCSF                   7149
#define IDC_EDIT_EXP                    7150
#define IDC_EDIT_LINE                   7151
#define IDC_EDIT_COUNT_IDW              7152
#define IDC_EDIT_COUNT_SPD              7153
#define IDC_EDIT_COUNT_MQF              7154
#define IDC_EDIT_COUNT_MLF              7155
#define IDC_EDIT_COUNT_TPSF             7156
#define IDC_EDIT_COUNT_NCSF             7157
#define IDC_EDIT_COUNT_EXP              7158
#define IDC_EDIT_COUNT_LINE             7159
#define IDC_BUTTON_CLEAR                7160
#define IDC_BUTTON_START                7162
#define IDC_EDIT_LSD                    7162
#define IDC_EDIT_LSD2                   7163
#define IDC_EDIT_LSD3                   7164
#define IDC_EDIT_LSD4                   7165
#define IDC_EDIT_LSD5                   7166
#define IDC_STATIC_INFO                 7167
#define IDC_EDIT_LSD6                   7168
#define IDC_RADIO_TE                    7169
#define IDC_RADIO_LSD                   7170
#define IDC_ZOOMIN                      12000
#define IDC_ZOOMOUT                     12001
#define IDC_PAN                         12002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        7043
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         7173
#define _APS_NEXT_SYMED_VALUE           7000
#endif
#endif
